import { CategoryType } from "@/types/category";

export const categories: CategoryType[] = [
  {
    id: "cat_01",
    title: "Laptops & Computers",
    description: "High-performance computers and laptops for work and gaming",
    slug: "laptops-computers",
    createdDate: "2024-01-15",
    updatedDate: "2024-03-20",
  },
  {
    id: "cat_02",
    title: "Smartphones & Tablets",
    description: "Latest mobile devices and accessories",
    slug: "mobile-devices",
    createdDate: "2024-01-15",
    updatedDate: "2024-03-18",
  },
  {
    id: "cat_03",
    title: "Gaming Accessories",
    description:
      "Gaming peripherals and accessories for ultimate gaming experience",
    slug: "gaming-accessories",
    createdDate: "2024-02-01",
    updatedDate: "2024-03-15",
  },
  {
    id: "cat_04",
    title: "Audio Equipment",
    description: "Professional audio gear and accessories",
    slug: "audio-equipment",
    createdDate: "2024-02-10",
    updatedDate: "2024-03-12",
  },
  {
    id: "cat_05",
    title: "Photography",
    description: "Cameras, lenses, and photography accessories",
    slug: "photography",
    createdDate: "2024-02-15",
    updatedDate: "2024-03-10",
  },
  {
    id: "cat_06",
    title: "Gaming Laptops",
    description: "High-performance laptops designed for gaming",
    slug: "gaming-laptops",
    createdDate: "2024-02-20",
    updatedDate: "2024-03-08",
  },
  {
    id: "cat_07",
    title: "Business Laptops",
    description: "Professional laptops for business and productivity",
    slug: "business-laptops",
    createdDate: "2024-02-25",
    updatedDate: "2024-03-05",
  },
  {
    id: "cat_08",
    title: "Smart Home",
    description: "Smart home devices and automation solutions",
    slug: "smart-home",
    createdDate: "2024-03-01",
    updatedDate: "2024-03-01",
  },
  {
    id: "cat_09",
    title: "Wearable Technology",
    description: "Smartwatches and fitness trackers",
    slug: "wearables",
    createdDate: "2024-03-05",
    updatedDate: "2024-03-05",
  },
  {
    id: "cat_10",
    title: "Networking Equipment",
    description: "Routers, switches, and networking accessories",
    slug: "networking",
    createdDate: "2024-03-10",
    updatedDate: "2024-03-10",
  },
];
