import { ChapterType } from "@/types/chapter.type";

export const chapters: ChapterType[] = [
    {
        id: "1",
        courseModuleId: "1",
        title: "NextJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "Meaning and basic syntax",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 1,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "2",
        courseModuleId: "2",
        title: "NextJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet girl!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 2,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "3",
        courseModuleId: "3",
        title: "NextJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet woman!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 3,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "4",
        courseModuleId: "4",
        title: "ReactJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "Meaning and basic syntax",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 4,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "5",
        courseModuleId: "5",
        title: "ReactJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet old man!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 5,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "6",
        courseModuleId: "6",
        title: "ReactJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet old man!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 6,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "7",
        courseModuleId: "7",
        title: "VueJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "Meaning and basic syntax",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 7,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "8",
        courseModuleId: "8",
        title: "VueJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet old man!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 7,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "9",
        courseModuleId: "9",
        title: "VueJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "what a skibidi toilet old man!",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 7,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "10",
        courseModuleId: "4",
        title: "ReactJS",
        description: "Skibidi toilet is the popular sci-fi cartoon for kid.",
        videoUrl: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        content: "Test skibidi",
        summary: "This cartoon will improve the imagination and creative. Everyone can watch and learn about the special each charactor such as Toilet man",
        duration: 6,
        orderIndex: 7,
        isPreview: true,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
]