import { CourseModuleType } from "@/types/course.type";

export const courseModule: CourseModuleType[] = [
    {
        id: "1",
        courseId: "1",
        title: "Introduction of Next.js",
        description: "Must know for beginner.",
        orderIndex: 1,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "2",
        courseId: "1",
        title: "Intermediate of Next.js",
        description: "Let's know about syntax and basic function for next level.",
        orderIndex: 2,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "3",
        courseId: "1",
        title: "Advance of Next.js",
        description: "Workshop for knowing error and adapt it to your imagination project",
        orderIndex: 3,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "4",
        courseId: "2",
        title: "Introduction of React.js",
        description: "Must know for beginner.",
        orderIndex: 1,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "5",
        courseId: "2",
        title: "Intermediate of React.js",
        description: "Let's know about syntax and basic function for next level.",
        orderIndex: 2,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "6",
        courseId: "2",
        title: "Advance of React.js",
        description: "Workshop for knowing error and adapt it to your imagination project",
        orderIndex: 3,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "7",
        courseId: "3",
        title: "Introduction of Vue.js",
        description: "Must know for beginner.",
        orderIndex: 1,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "8",
        courseId: "3",
        title: "Intermediate of Vue.js",
        description: "Let's know about syntax and basic function for next level.",
        orderIndex: 2,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
    {
        id: "9",
        courseId: "3",
        title: "Advance of Vue.js",
        description: "Workshop for knowing error and adapt it to your imagination project",
        orderIndex: 3,
        createdAt: "2021-09-01",
        updatedAt: "2021-09-01",
    },
]
