import { RewardType } from "@/types/reward";

export const rewards: RewardType[] = [
  {
    id: "1",
    name: "Free Coffee",
    description:
      "Enjoy a warm, freshly brewed coffee of your choice from participating cafes. Whether you prefer a classic espresso, a creamy latte, or a rich mocha, this reward lets you savor a comforting coffee experience to start your day off right.",
    thumbnail: "/mockup.jpg",
    type: "Food & Beverage",
    points: 100,
    stock: 50,
    status: "Available",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-10",
  },
  {
    id: "2",
    name: "Movie Ticket",
    description:
      "Get a complimentary movie ticket to see any film of your choice at selected theaters. Escape into a cinematic experience, whether you're in the mood for action, romance, or comedy, and enjoy a night out with friends or family.",
    thumbnail: "/mockup.jpg",
    type: "Entertainment",
    points: 200,
    stock: 30,
    status: "Available",
    createdAt: "2024-01-05",
    updatedAt: "2024-01-15",
  },
  {
    id: "3",
    name: "Gift Card",
    description:
      "Receive a $10 gift card redeemable at various popular retail stores and online shops. Use it to treat yourself to a new item on your wishlist or put it towards a special purchase for a loved one.",
    thumbnail: "/mockup.jpg",
    type: "Gift",
    points: 300,
    stock: 20,
    status: "Available",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-20",
  },
  {
    id: "4",
    name: "Spa Day Pass",
    description:
      "Indulge in a day of relaxation and rejuvenation with a premium spa day pass. Enjoy access to soothing treatments like massages, facials, and saunas, and let go of all your stress for a few blissful hours.",
    thumbnail: "/mockup.jpg",
    type: "Wellness",
    points: 500,
    stock: 15,
    status: "Limited",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-10",
  },
  {
    id: "5",
    name: "Dinner for Two",
    description:
      "Treat yourself and a guest to a memorable dining experience at a fine restaurant, complete with an exquisite menu and ambiance. Enjoy a night out savoring gourmet dishes and quality time with someone special.",
    thumbnail: "/mockup.jpg",
    type: "Food & Beverage",
    points: 600,
    stock: 10,
    status: "Available",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-25",
  },
  {
    id: "6",
    name: "Fitness Class",
    description:
      "Join a high-energy fitness class to boost your health and wellness. From yoga and Pilates to strength training and cardio, this reward helps you stay active and motivated on your fitness journey.",
    thumbnail: "/mockup.jpg",
    type: "Wellness",
    points: 150,
    stock: 25,
    status: "Available",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-10",
  },
  {
    id: "7",
    name: "Concert Tickets",
    description:
      "Enjoy a night of live music with two concert tickets for you and a friend. Experience the thrill of seeing your favorite artist or band perform live and make lasting memories together.",
    thumbnail: "/mockup.jpg",
    type: "Entertainment",
    points: 700,
    stock: 5,
    status: "Limited",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-15",
  },
  {
    id: "8",
    name: "Travel Voucher",
    description:
      "Redeem a $50 travel voucher and use it to cover expenses on your next getaway. Whether you’re looking to explore a new city, enjoy a staycation, or take a road trip, this reward makes traveling more affordable.",
    thumbnail: "/mockup.jpg",
    type: "Travel",
    points: 800,
    stock: 8,
    status: "Available",
    createdAt: "2024-03-20",
    updatedAt: "2024-03-30",
  },
  {
    id: "9",
    name: "Online Course",
    description:
      "Get exclusive access to an online course in a subject of your choice. Expand your knowledge or pick up a new skill, from creative writing to programming or marketing, with professional instruction and support.",
    thumbnail: "/mockup.jpg",
    type: "Education",
    points: 350,
    stock: 12,
    status: "Available",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-10",
  },
  {
    id: "10",
    name: "Charity Donation",
    description:
      "Make a meaningful contribution by donating $5 to a charity of your choice. Support causes you care about, from animal welfare to environmental protection, and help make a positive impact in the world.",
    thumbnail: "/mockup.jpg",
    type: "Charity",
    points: 100,
    stock: 100,
    status: "Available",
    createdAt: "2024-04-15",
    updatedAt: "2024-04-20",
  },
];
